[package]
name = "primefactor"
version = "0.1.0"
authors = ["sidrashakeel19 <sidrashakeel19@hotmail.com>"]
edition = "2018"
description = "Library for finding whether a number is prime or not and also determine its factors"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
